apiVersion: batch/v1
kind: Job
metadata:
  name: cfdwid-lr-train
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cfdwid-lr-train
          image: jkieley/cfdwid_lr_train:latest
          env:
            - name: INPUT_CSV_FILE_PATH
              value: "/app/mnt/creditcard_large.csv"
            - name: INPUT_CSV_FILE_NAME
              value: "creditcard_large.csv"
            - name: OUTPUT_MODEL_FOLDER_PATH
              value: /app/mnt
            - name: OUTPUT_FILE_SUFFIX
              value: {{runId}}
            - name: AWS_SERVER_PUBLIC_KEY
              value: "$AWS_KEY"
            - name: AWS_SERVER_SECRET_KEY
              value: "$AWS_ACCESS_KEY"
            - name: REGION_NAME
              value: us-east-1
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /app/mnt
              name: test-volume
          resources:
            limits:
              memory: "2500Mi"
              cpu: "2"
            requests:
              memory: "2500Mi"
              cpu: "2"
      volumes:
        - name: test-volume
          hostPath:
            path: /to-mount-data-dir
            type: DirectoryOrCreate
      restartPolicy: Never
  backoffLimit: 20
